name: CI/CD

on:
  push:
    branches: [ "server" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - run: mkdir ./src/main/resources
      - run: touch ./src/main/resources/application-prod.yml
      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application-prod.yml
      - run: cat ./src/main/resources/application-prod.yml

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test -i --no-daemon -Dspring.profiles.active=prod

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for ARM64
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --tag ${{ secrets.DOCKER_USERNAME }}/todo:latest \
            --output type=docker \
            .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/todo:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to App Center Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu
            docker pull ${{ secrets.DOCKER_USERNAME }}/todo:latest

            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > .env

            if [ "$(docker ps -aq -f name=todo)" ]; then
              docker stop todo
              docker rm todo
            fi

            docker run -d \
              --name todo \
              -p 8080:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              ${{ secrets.DOCKER_USERNAME }}/todo:latest
