name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
	
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
	
      - name: make application.properties
        if: contains(github.ref, 'main')
        run: |
          mkdir -p ./src/main/resources  # -p 옵션 추가
          cd ./src/main/resources
          touch ./application.properties
          echo "${{ secrets.APPLICATION }}" > ./application.properties  # Secrets 값 확인

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Send file to the server
        uses: appleboy/scp-action@v0.1.0  # 안정적 버전으로 수정
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.SSH_PORT }}
            source: "./build/libs/*.jar"
            target: download

      - name: Deploy remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.0  # 안정적 버전으로 수정
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            sh deploy/deploy.sh
